docs(spec): add develop spec for documents and workflow
lawporter/spec pull request #1
Opened 2022-01-21 13:37 UTC by linxuyalun

PR 主要内容为对 lawporter 未来整体的工作流程规范撰写的第一份简易的规约文档

暂时想到的比较 general 的部分只有这么多，大家看看有没有什么不合理的、需要讨论的以及遗漏的内容

后续会再补一些图例

2022-01-21 14:59 UTC, Thrimbda requested changes

2022-01-21 14:59 UTC, Thrimbda commented on README.md
> +考虑到目前我们组织的架构性问题与项目的特点，使用一个**规范目录结构的集中性文档管理**是一个比较好的方案。
类似 wiki 这种？

2022-01-21 14:59 UTC, Thrimbda commented on README.md
> +**删除 Git 分支**：一旦开发人员的分支被合并，这证明该分支已经完成了它的任务，项目负责人应该（**SHOULD**）删除该分支，从而避免其他开发人员意外的使用了旧分支。
> 项目负责人应该（**SHOULD**）删除该分支

应该采用自动化手段，Github 应该就提供这个功能

2022-01-21 14:59 UTC, Thrimbda commented on README.md
> +**合并一个 Pull Request**：一旦开发人员的 PR 被审核通过，如果代码没有冲突，项目负责人必须（**MUST**）使用 **Squash and merge** 合并代码，如下图：
>  **Squash and merge**

应该在 repo 中开启设置禁用其他两种

2022-01-21 14:59 UTC, Thrimbda commented on README.md
> +5. 单次 PR 的代码修改量不应该（**SHOULD NOT**）超过一定行数（比如说 300 行），测试代码或一些整体性代码的变更不算在內。不同项目对于单个 PR 的代码修改量行数可以（**MAY**）自行约定；
添加一条强调一下：超过 500 行，reviewer 有权拒绝 review，这点很重要，规定了 reviewer 的权利，和 committer 的义务对应起来

2022-01-21 14:59 UTC, Thrimbda commented on README.md
> +6. 当单次 PR 的代码修改量超过一定行数时（比如说 200 行，由项目团队自行约定）或该 PR 涉及修改的内容众多时，开发人员应（**SHOULD**）发起一次会议评审，将代码核心内容做一次系统性介绍帮助他人审查；
200 就评审感觉少了，经验看来 300 行以上发起代码评审比较合适；但是代码评审不能代替代码 review，因为不同 reviewer 理解不同 committer 的代码需要的时间不同，同步进行容易略过一些东西

2022-01-21 14:59 UTC, Thrimbda commented on README.md
> +5. 不能（**MUST NOT**）使用无意义的纯数字作为分支名的一部分，比如 `fix/128`。
FYI， 例如 `feat/homepage` 这样的分支被创建的时候， git 会认为 `feat` 部分构成一个目录，因此不再允许叫做 `feat` 的分支被创建出来

2022-01-22 03:37 UTC, linxuyalun commented on README.md
> +考虑到目前我们组织的架构性问题与项目的特点，使用一个**规范目录结构的集中性文档管理**是一个比较好的方案。
加了点 examples 和使用该方案的原因

2022-01-22 03:55 UTC, linxuyalun commented on README.md
> +**合并一个 Pull Request**：一旦开发人员的 PR 被审核通过，如果代码没有冲突，项目负责人必须（**MUST**）使用 **Squash and merge** 合并代码，如下图：
增加了相关截图

2022-01-22 04:04 UTC, linxuyalun commented on README.md
> +5. 单次 PR 的代码修改量不应该（**SHOULD NOT**）超过一定行数（比如说 300 行），测试代码或一些整体性代码的变更不算在內。不同项目对于单个 PR 的代码修改量行数可以（**MAY**）自行约定；
调整了行文

2022-01-22 04:04 UTC, linxuyalun commented on README.md
> +6. 当单次 PR 的代码修改量超过一定行数时（比如说 200 行，由项目团队自行约定）或该 PR 涉及修改的内容众多时，开发人员应（**SHOULD**）发起一次会议评审，将代码核心内容做一次系统性介绍帮助他人审查；
200 是一个随意放的数字，调整了行文

2022-01-22 04:04 UTC, linxuyalun commented on README.md
> +6. 当单次 PR 的代码修改量超过一定行数时（比如说 200 行，由项目团队自行约定）或该 PR 涉及修改的内容众多时，开发人员应（**SHOULD**）发起一次会议评审，将代码核心内容做一次系统性介绍帮助他人审查；
200 是一个随意放的数字，调整了行文

2022-01-22 04:08 UTC, linxuyalun commented on README.md
> +5. 不能（**MUST NOT**）使用无意义的纯数字作为分支名的一部分，比如 `fix/128`。
even better

2022-01-22 04:50 UTC, linxuyalun commented on README.md
> +5. 不能（**MUST NOT**）使用无意义的纯数字作为分支名的一部分，比如 `fix/128`。
文中添加了对这种 case 的描述

2022-01-22 05:09 UTC, linxuyalun commented on README.md
> +**删除 Git 分支**：一旦开发人员的分支被合并，这证明该分支已经完成了它的任务，项目负责人应该（**SHOULD**）删除该分支，从而避免其他开发人员意外的使用了旧分支。
done

2022-01-22 06:34 UTC, jiangzhao2018 commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
是不是可以考虑用 `/` 连接后缀来说明 base 分支，比如 `feat/project-intro/master`， 因为实际开发中可能在一定周期内 master 和 develop 分支是不一致的，持续开发中的新分支可能基于 develop，一些热修补丁可能基于 master

2022-01-22 07:45 UTC, linxuyalun commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
我的本意是为了去掉语义不清晰的分支而完全语义化。考虑了一下这种 case，可能出现的情况是在一段时期内完成一个功能 A，那我觉得应该是 `feat/A/main`，然后从这里划分出来的新分支就是 `feat/A/something`。你觉得这样子是否能够 cover 掉你描述的这种场景

2022-01-22 07:45 UTC, linxuyalun commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
另外这种情况我觉得是可能较高频率出现的，我们是不是要考虑增加一条规约来描述这种情况的通用命名规则

2022-01-22 09:05 UTC, jiangzhao2018 commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
我觉得需要一个统一的规约， 针对功能A，我们在开发过程中，这块功能可能是协作开发的，那我们应该有一个共同的开发分支 feat/A/dev，然后不同的开发人员可以创建自己的分支 feat/A/dev-开发人员姓名-版本号， 相应的通过自己分支向 feat/A/dev 提 pr，功能开发完全后，再由 feat/A/dev 向 main(master) 分支提 pr；或者不需要 /dev 的后缀， 相关开发人员就以 feat/A/开发人员姓名-版本号 命名自己分支

2022-01-22 13:59 UTC, linxuyalun commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
已将此作为一个规约，但是我没有将 “开发人员-版本号” 作为一个强制约束，在目前的规约中，我更期望分支名与类型和功能绑定而不是与具体开发人员绑定，即侧重于“这个分支做的事情是什么“而不是”这个分支是谁负责的“

2022-01-23 09:16 UTC, Thrimbda commented
另外整体文档应该是演进的而不是死板的，文档 owner 应该定期维护其时效性确保其符合最新情况，文档面向的所有的人都有权对文档提出修改意见，文档修改也应该发起评审等活动（不一定需要是同步评审，异步评审最好，但也应该承认有部分人出于各种原因没有认真阅读/评审文档，但只要他是文档的受众，迟早要认真阅读，因此文档应该长期保持开放评论，从而被大家充分理解和认同）；过期文档应该被明确归档，总之目的是为了更好地信息同步，原则上不应该在任何地方死板

2022-01-23 09:17 UTC, Thrimbda commented on README.md
> +5. 单次 PR 的代码修改量应该（**SHOULD NOT**）控制在 300 行左右（不同组织自行约定），测试代码或一些整体性代码变更不算在內；当 PR 代码修改量超过 500 行（不同组织自行约定），审查人员应当（**SHOULD**）拒绝此次 review；
should not?

2022-01-23 09:17 UTC, Thrimbda commented on README.md
> +5. 单次 PR 的代码修改量应该（**SHOULD NOT**）控制在 300 行左右（不同组织自行约定），测试代码或一些整体性代码变更不算在內；当 PR 代码修改量超过 500 行（不同组织自行约定），审查人员应当（**SHOULD**）拒绝此次 review；
随着经验的丰富，希望能逐渐明确出什么情况可以算作例外（现在拍脑袋想出所有的不太合理）

2022-01-23 11:08 UTC, linxuyalun commented
> 另外整体文档应该是演进的而不是死板的，文档 owner 应该定期维护其时效性确保其符合最新情况，文档面向的所有的人都有权对文档提出修改意见，文档修改也应该发起评审等活动（不一定需要是同步评审，异步评审最好，但也应该承认有部分人出于各种原因没有认真阅读/评审文档，但只要他是文档的受众，迟早要认真阅读，因此文档应该长期保持开放评论，从而被大家充分理解和认同）；过期文档应该被明确归档，总之目的是为了更好地信息同步，原则上不应该在任何地方死板

确实如此，按目前的计划，也是先试试行一段时间再回头重新评估

2022-01-23 11:08 UTC, linxuyalun commented on README.md
> +5. 单次 PR 的代码修改量应该（**SHOULD NOT**）控制在 300 行左右（不同组织自行约定），测试代码或一些整体性代码变更不算在內；当 PR 代码修改量超过 500 行（不同组织自行约定），审查人员应当（**SHOULD**）拒绝此次 review；
typo，done

2022-01-23 11:22 UTC, linxuyalun commented
> 另外整体文档应该是演进的而不是死板的，文档 owner 应该定期维护其时效性确保其符合最新情况，文档面向的所有的人都有权对文档提出修改意见，文档修改也应该发起评审等活动（不一定需要是同步评审，异步评审最好，但也应该承认有部分人出于各种原因没有认真阅读/评审文档，但只要他是文档的受众，迟早要认真阅读，因此文档应该长期保持开放评论，从而被大家充分理解和认同）；过期文档应该被明确归档，总之目的是为了更好地信息同步，原则上不应该在任何地方死板

issue 是用来长期保持开放评论的最直接有效的方式，规约的更新会被记录在一个 CHANGELOG 文件中，并描述改了哪些以及为什么这么改（显然它们可以对应到 issue 和 pr 中）

这些更新都是在这次 pr 第一次合并之后，这次 pr 也作为版本 v0.1 发布。后续根据大家的实际使用体验更新规约内容与版本

2022-01-24 04:51 UTC, KONY128 requested changes
PTAL

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +| 产品业务功能 | 产品文档 | 用以说明本产品具有的业务功能，大模块下应当还会作进一步细分，<br/>比如业务子模块、需求变更、用户反馈等。这部分和业务紧绑定，不做展开。 |
不建议在此处加换行。换行使得该表格在小屏设备下阅读体验很差

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +* 分布式：即各个 repo 下各自维护各自的文档。这样的好处是很多东西都可以就地查找，不需要去另外一个 repo 寻找；坏处是一个 repo 下的文档不可避免的有许多重复的东西。通常来说，一个以项目为单位进行主要维护的组织会将 repo 和相关文档放置在一起，比如说 [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)；
这里不太容易理解。

> 一个以项目为单位进行主要维护的组织会将 repo 和相关文档放置在一起，比如说 [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)

我想这里的`项目`是指 repo？这里是不是想表达这种文档组织形式会把文档分散在各个子 repo 中？

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +* 集中式：集中式是将所有文档放在一个统一的地方进行管理。这样的好处是方便组织管理，并且文档的结构可以更加清晰，项目间的查询也更加方便，方便迁移；坏处是开发者不得不同时维护多个 repo，文档与 repo 之间的对齐需要另外约定。一个需要负责多个 repo 且需要协调多个 repo 的组织通常会使用集中式的文档管理，比如说 [fission](https://github.com/fission
这里也不太容易理解。

> 集中式是将所有文档放在一个统一的地方进行管理。

我想这里的 `统一的地方` 是不是指一个 repo？这里是不是想表达`集中式`是把所有的文档放在一个 repo 里管理？

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +* 集中式：集中式是将所有文档放在一个统一的地方进行管理。这样的好处是方便组织管理，并且文档的结构可以更加清晰，项目间的查询也更加方便，方便迁移；坏处是开发者不得不同时维护多个 repo，文档与 repo 之间的对齐需要另外约定。一个需要负责多个 repo 且需要协调多个 repo 的组织通常会使用集中式的文档管理，比如说 [fission](https://github.com/fission
> 坏处是开发者不得不同时维护多个 repo

这里的 repo 指哪个 repo？

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +考虑到目前我们组织的架构性问题与项目的特点，组织下涉及多个 repo 及其相互之间的合作，因此使用一个**规范目录结构的集中性文档管理**是一个比较好的方案。
在这一小节中，文档管理上的 “分布式” 和 “集中式” 有权威定义吗？我没有 Google 到文档管理方面这两个定义的专有名词。

要不要考虑特别说明这两个词是本文 Glossary 专属？因为常见的 “分布式” 和 “集中式” 的定义一般描述计算形式或存储形式，而事物的组织形式鲜有这样的表述。

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +一个运作良好的开发团队会按照一定的规范流程进行项目的开发，这类流程规范称为 Git Workflow，常见的 4 种工作流模型有 Git Flow、Github Flow、GitLab Flow 和 One Flow，*[4 branching workflows for Git](https://medium.com/@patrickporto/4-branching-workflows-fo
这里对该专有名词的定义不太准确。

> 一个运作良好的开发团队会按照一定的规范流程进行项目的开发，这类流程规范称为 Git Workflow

如[这篇文章](https://www.atlassian.com/git/tutorials/comparing-workflows)所言，Git Workflow 是**专指**在 Git 工具上的，常伴有自动化过程的开发流程。

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +2. 一个 PR 只做（**MUST**）一件事情（比如一个优化，一个功能），如果一个 PR 同时包含几件事情请关闭它必将它拆分成几个 PR 重新提交；
这个约束看起来不是这么直观，我认为这里可以补充这样做的原因。

因为所有 pr 的 branch 都会被 squash，所以 pr 被“降维”成了 commit，pr 也应该如 commit 一般，一个 commit 只做一件事。

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +6. 每次 PR 应（**SHOULD**）保证项目团队成员超过半数的人员审查过代码内容后才能合并 PR，每个 PR 应当（**SHOULD**）在发起后的 24 小时内完成 review；
异议。

1. majority 的约束对于小团队才适用，且应明确划分好`团队`的定义。`审查人员`应该是 pr 中对应功能、修改所涉及的相关人员（包括开发者、小组领导、对接人等，一般不宜超过 8 人）的一半以上，而不是团队成员。

2. 应当发起后 1 个工作日内完成，而非 24 小时。

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +7. 当单次 PR 的代码修改量超过 300 行时（组织自行约定）或该 PR 涉及修改的内容众多时，除了审查人员审查代码外，开发人员还应（**SHOULD**）发起一次会议评审，将代码核心内容做一次系统性介绍帮助他人审查；
此处的用词有些奇怪。

> 当单次 PR 的代码修改量超过 300 行时（组织自行约定）或该 PR 涉及修改的内容众多时

众多 -> 较多

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +开发者创建一个新的分支时，是为了开发一个功能、修复一些 Bug 或者其他事，这些分支最后会被合并到主分支上。一个分支上要做的事情在创建时已经是明确的，一个分支上做的所有事情在合并到主分支上时也会最终被合并为一次 commit（见[开发工作流规范](#开发工作流规范)），基于此，本文参考了其他开发者对分支命名的[思考](https://stackoverflow.com/questions/273
此处语句有些不通畅。

> 本文参考了其他开发者对分支命名的思考并根据本文对 Git Commit 规范约定了分支语义化规范：

本文参考了其他开发者对分支命名的思考并结合了本文对 Git Commit 规范的约定，提出分支语义化规范。

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
异议。

我认为这是一个很糟糕的命名方式。非强约束的 scope、单词数量的多寡都会使得我们可用的分支名十分有限，**因为一个文件只可能是 regular file 和 directory 之一**。

我认为使用 `.` 或者 `_` 代替空格都是不错的选择，而不应该用 `/`。这种涉及到文件夹的 branch 具体怎么辅助我们以更好地进行开发仍需要仔细斟酌。

2022-01-24 04:51 UTC, KONY128 commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
我觉得此处以及前文提到的用版本号作分支名的形式可以补充说说明，为何多数开源项目这样命名分支，而对于较一般的企业开发而言不适合。

我认为这是有深层原因的。大部分大型开源项目每个版本要发布什么内容已经早早定好，所以才会有 develop-0.33，release-0.32 这类的分支名。

在企业内部面临的多变的业务往往要求我们开发过程敏捷，我们无法预知接下来会有什么功能或改动，所以才有必要在分支名上补充充足的信息，以供管理和审查。

2022-01-24 04:56 UTC, KONY128 commented
挺不错的，点赞

2022-01-24 04:57 UTC, KONY128 commented
目前我们已经有了项目的 Git 开发规范以及 README 规范，还差很多重要规范。你打算怎么处理，需要我帮忙吗？

2022-01-24 05:13 UTC, linxuyalun commented on README.md
> +| 产品业务功能 | 产品文档 | 用以说明本产品具有的业务功能，大模块下应当还会作进一步细分，<br/>比如业务子模块、需求变更、用户反馈等。这部分和业务紧绑定，不做展开。 |
我屏幕试了一下感觉还行啊，不知道你说的阅读很差指的是啥

2022-01-24 05:19 UTC, linxuyalun commented on README.md
> +| 产品业务功能 | 产品文档 | 用以说明本产品具有的业务功能，大模块下应当还会作进一步细分，<br/>比如业务子模块、需求变更、用户反馈等。这部分和业务紧绑定，不做展开。 |
![image](https://user-images.githubusercontent.com/25969296/150726149-d7218532-2014-44a0-bde8-254f1fc78f7f.png)

设置 br 是为了避免用电脑阅读时由于 描述 太长导致文档和类型变成两行

2022-01-24 05:19 UTC, linxuyalun commented on README.md
> +* 分布式：即各个 repo 下各自维护各自的文档。这样的好处是很多东西都可以就地查找，不需要去另外一个 repo 寻找；坏处是一个 repo 下的文档不可避免的有许多重复的东西。通常来说，一个以项目为单位进行主要维护的组织会将 repo 和相关文档放置在一起，比如说 [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)；
repo 调整为 项目；这句话重新表述了

2022-01-24 05:20 UTC, linxuyalun commented on README.md
> +考虑到目前我们组织的架构性问题与项目的特点，组织下涉及多个 repo 及其相互之间的合作，因此使用一个**规范目录结构的集中性文档管理**是一个比较好的方案。
没有集中定义，所以我规约里写的是“处理方式”，而不是说它们的归类

2022-01-24 05:22 UTC, linxuyalun commented on README.md
> +一个运作良好的开发团队会按照一定的规范流程进行项目的开发，这类流程规范称为 Git Workflow，常见的 4 种工作流模型有 Git Flow、Github Flow、GitLab Flow 和 One Flow，*[4 branching workflows for Git](https://medium.com/@patrickporto/4-branching-workflows-fo
因此我在规约假设里说明了一下“开发规范假定组织下的所有开发者均使用 Git 作为代码版本控制工具，并假设读者对 Git 已经有了一定的了解。”，所以后文默认所有工作都是 git 相关的

2022-01-24 05:25 UTC, linxuyalun commented on README.md
> +* 集中式：集中式是将所有文档放在一个统一的地方进行管理。这样的好处是方便组织管理，并且文档的结构可以更加清晰，项目间的查询也更加方便，方便迁移；坏处是开发者不得不同时维护多个 repo，文档与 repo 之间的对齐需要另外约定。一个需要负责多个 repo 且需要协调多个 repo 的组织通常会使用集中式的文档管理，比如说 [fission](https://github.com/fission
用 `地方` 是因为可能是一个统一的文档管理应用，也可能是某一个 repo，所以没有指定内容

2022-01-24 05:27 UTC, linxuyalun commented on README.md
> +* 集中式：集中式是将所有文档放在一个统一的地方进行管理。这样的好处是方便组织管理，并且文档的结构可以更加清晰，项目间的查询也更加方便，方便迁移；坏处是开发者不得不同时维护多个 repo，文档与 repo 之间的对齐需要另外约定。一个需要负责多个 repo 且需要协调多个 repo 的组织通常会使用集中式的文档管理，比如说 [fission](https://github.com/fission
> > 坏处是开发者不得不同时维护多个 repo
> 
> 这里的 repo 指哪个 repo？

已删除这句话，“文档与 repo 之间的对齐需要另外约定” 就是对它的解释。

2022-01-24 05:28 UTC, KONY128 commented on README.md
> +| 产品业务功能 | 产品文档 | 用以说明本产品具有的业务功能，大模块下应当还会作进一步细分，<br/>比如业务子模块、需求变更、用户反馈等。这部分和业务紧绑定，不做展开。 |
窄屏下的观看体验确实比较差，看起来杂乱无章。你可以试试 Chrome 自带的移动端视角。

<img width="452" alt="截屏2022-01-24 下午1 26 50" src="https://user-images.githubusercontent.com/41882659/150727008-ec54c718-2d77-4ea9-8e2b-2db865bc36b6.png">

2022-01-24 05:29 UTC, linxuyalun commented on README.md
> +一个运作良好的开发团队会按照一定的规范流程进行项目的开发，这类流程规范称为 Git Workflow，常见的 4 种工作流模型有 Git Flow、Github Flow、GitLab Flow 和 One Flow，*[4 branching workflows for Git](https://medium.com/@patrickporto/4-branching-workflows-fo
已对这句话进行了一点调整

2022-01-24 05:37 UTC, linxuyalun commented on README.md
> +2. 一个 PR 只做（**MUST**）一件事情（比如一个优化，一个功能），如果一个 PR 同时包含几件事情请关闭它必将它拆分成几个 PR 重新提交；
updated

2022-01-24 05:40 UTC, linxuyalun commented on README.md
> +6. 每次 PR 应（**SHOULD**）保证项目团队成员超过半数的人员审查过代码内容后才能合并 PR，每个 PR 应当（**SHOULD**）在发起后的 24 小时内完成 review；
团队成员 -》 团队开发成员 应该可以消除歧义

2022-01-24 05:40 UTC, linxuyalun commented on README.md
> +7. 当单次 PR 的代码修改量超过 300 行时（组织自行约定）或该 PR 涉及修改的内容众多时，除了审查人员审查代码外，开发人员还应（**SHOULD**）发起一次会议评审，将代码核心内容做一次系统性介绍帮助他人审查；
done

2022-01-24 05:54 UTC, linxuyalun commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
相反，我目前的看法其实确实是希望加大对分支命名的约束，基于以下几点原因：
1. 短期的分支其实大多数人是不在意分支名的，它很快就会被合并；
2. 真正在意的分支名都是中期内或长期留存的，因此它具有一定的含义，比如说某一段时间围绕某一个功能开发，这种时候才会关注分支名的含义。“/“ 起到了辅助分类的作用；
3. 我目前是想要 ”/“ 作为辅助的，”/“ 确实会带来命名的限制，但是自动删除分支的策略给我觉得不会使得分支名陷入”命名难“的窘境，我暂时认为它是往更规范更语义化的的命名流程靠拢

但是这些规范也没有完整的实施过，具体效果还需要事实验证，我希望能够试推行它们一段时间后再做评估

2022-01-24 06:08 UTC, linxuyalun commented on README.md
> +使用该分支命名规则兼具简明性与可读性。另一种常被开发人员采用的分支命名规约是使用 `master`、`develop`、 `release-*` 或 `hotfix-*` 中的一个。这种命名方式来源于 [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) 工作流程中的一环，然而，本文认为这种命名不足以表达全部的语
uodated

2022-01-24 06:08 UTC, linxuyalun commented on README.md
> +开发者创建一个新的分支时，是为了开发一个功能、修复一些 Bug 或者其他事，这些分支最后会被合并到主分支上。一个分支上要做的事情在创建时已经是明确的，一个分支上做的所有事情在合并到主分支上时也会最终被合并为一次 commit（见[开发工作流规范](#开发工作流规范)），基于此，本文参考了其他开发者对分支命名的[思考](https://stackoverflow.com/questions/273
done

2022-01-24 08:08 UTC, linxuyalun commented on README.md
> +| 产品业务功能 | 产品文档 | 用以说明本产品具有的业务功能，大模块下应当还会作进一步细分，<br/>比如业务子模块、需求变更、用户反馈等。这部分和业务紧绑定，不做展开。 |
根据行文的断句放置了 br 符号

2022-01-24 09:20 UTC, KONY128 commented on README.md
> +| 产品业务功能 | 产品文档 | 用以说明本产品具有的业务功能，大模块下应当还会作进一步细分，<br/>比如业务子模块、需求变更、用户反馈等。这部分和业务紧绑定，不做展开。 |
体验好了许多 👍

2022-01-24 09:22 UTC, KONY128 commented on README.md
> +* 分布式：即各个 repo 下各自维护各自的文档。这样的好处是很多东西都可以就地查找，不需要去另外一个 repo 寻找；坏处是一个 repo 下的文档不可避免的有许多重复的东西。通常来说，一个以项目为单位进行主要维护的组织会将 repo 和相关文档放置在一起，比如说 [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)；
👍

2022-01-24 09:25 UTC, KONY128 commented on README.md
> +考虑到目前我们组织的架构性问题与项目的特点，组织下涉及多个 repo 及其相互之间的合作，因此使用一个**规范目录结构的集中性文档管理**是一个比较好的方案。
了解了，我感觉 “分别管理” 与 “集中管理” 可能更符合这里的语义，但字却变多了。

“分布式” 这一表述有些不太直观，但如果没有更好的表述就用它好了。

2022-01-24 09:27 UTC, KONY128 commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
我觉得问题不是在于远程库中的分支管理，而在于本地库的分支情况。

在开发者拉取项目时很可能把一些 traisient 的分支拉取下来，限制了开发者可用的分支名。

开发者在本地要做很多分支删除操作，比较繁琐。

2022-01-24 09:35 UTC, KONY128 commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
我觉得问题出在可选的 scope 上，`type` 作为顶层结构是与其下的 `scope` 与 `name` 确实是有树型的父子关系，可以很好的应用到文件系统中，但 `scope` 与 `name` 之间有很多 tricky 的情况，并不一定是文件系统的树型关系。

我认为换用 `.` 会比较合适，避免了分隔符隐含的各个 field 之间的树型父子关系。这样就可以避免 `fix/home` 与 `fix/home/footer` 之间无法同时存在于一个 git 库中的窘境。

2022-01-24 10:16 UTC, linxuyalun commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
`/` 只是为了表述层级的关系，`\` 确实会导致目录与分支名带来的冲突，使用 `.` 或许是个更好的描述，我觉得没有什么问题了

2022-01-24 10:19 UTC, linxuyalun commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
@jiangzhao2018 @Thrimbda 两位怎么看。我目前觉得 `.` 作为 token 不会有问题，也不会有目录的问题

2022-01-24 10:28 UTC, linxuyalun commented
> 目前我们已经有了项目的 Git 开发规范以及 README 规范，还差很多重要规范。你打算怎么处理，需要我帮忙吗？

看看后面缺些啥，如果有啥能一起写的再好不过了

2022-01-24 11:53 UTC, Thrimbda commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
我建议保留 `type` 后的 `/`，这是有意而为之的，明确我们不希望开发者起 `feat` 或者 `release` 这样的分支名，至于 `scope` 和 `name` 如何连接我觉得不关键，使用 `-` 和`.` 应该跟团队习惯对齐

2022-01-25 09:18 UTC, linxuyalun commented on README.md
> +> 需要注意的是，使用这种方式会限制一些分支名的创建。比如说开发人员 A 创建了分支 `feat/homepage/intro`，则其他开发人员无法创建诸如  `feat/homepage` 这样的分支名，因为 git 会视 `feat` 和 `homepage` 部分为目录名，`intro` 为分支路径名；同理 `feat/homepage/intro/blabla` 也是不被允许的。读者可以
done

2022-01-25 09:21 UTC, linxuyalun commented
我认为我们已经进行了充分的讨论并且达成了共识，这次讨论是充分且卓有成效的 🍻

是时候发布 0.1.0 的规约了

2022-01-25 09:21 UTC, merged